### ISSUE TITLE
Example doesn't work. "GWCA/APIMain.h" not found

### ISSUE THREAD

**Issue by makryno** [GregLando113/GWCA#11]
The provided example in the readme does not work.
When I try to build it I get the that the file "GWCA/APIMain.h" cannot be found.
I have followed every other steps in the readme (added GWCA as a git submodule, added it as a project in VC, defined it as a dependency and added it as a reference).

**Comment by ldufr** [comment]
Hi, I'm currently working on that and also to provide more examples.

The documentation and examples are super outdated.

**Comment by ldufr** [comment]
I added 2 examples so hopefully it will help you.
