### ISSUE TITLE
GW::Agents::Move(x, y) crashes the game client

### ISSUE THREAD

**Issue by AnonymousII** [GregLando113/GWCA#13]
Hi,

when using the function GW::Agents::Move(x, y) it just crashes the game client for me.
Initialize() returned true before and other API functions seem to work (e.g. reading the player coordinates or map id), so I guess the API startup itself is performed corectly.

However inside Toolbox the very same function call (even with the same coordinates on the same map in the same instance) works just fine and the character starts moving to the specified position when setting a corresponding hotkey for it.

On the other hand, there seems to be any kind of initialization missing: When I download GWToolbox, build it from source and slightly modify the code in GWToolbox.cpp to use GW::Agents::Move(x, y) right after enabling the HookBase hooks(see code snippet below) it also crashes the game client from inside toolbox:
https://github.com/HasKha/GWToolboxpp/blob/f325d384b5cddc2505aea6134019150f4dcf9da1/GWToolbox/GWToolbox/GWToolbox.cpp#L94-L97

Therefore I must be missing any kind of initialization Toolbox does before enabling the move hotkeys. Are there any further requirements / initializations / etc. before I can use GW::Agents::Move(x, y) in order to not crash the game client? Toolbox seems to do them after enabling the HookBase hooks and before a move hotkey is executed.

The game tries to Read Memory at address 0x14 which fails for obvious reasons.

Thans in advance.

**Comment by GregLando113** [comment]
The move function must be called within the game thread. We have facilites to do this from any thread via gamethreadmgr if you need to do this outside of the gamethreads, sorry this isnt better documented.

**Comment by AnonymousII** [comment]
Thanks a lot! That was exactly what I was missing - when calling `GW::GameThread::Enqueue([x, y] {GW::Agents::Move(x, y); });` instead it works perfectly fine :)

Would be really great if you could add some documentation to the GameThreadManager which functions need to be called out of a game thread and maybe a hint to the functions in the corresponding header files since it takes really long to find this out by yourself... (At least adding a list of these functions will hopefully not take too much time)

**Comment by ldufr** [comment]
Every game function should be called from the game thread to be safe. We can't give much guarantees, because we don't control the game code.
