### ISSUE TITLE
access violation

### ISSUE THREAD

**Issue by gwmai** [GregLando113/GWCA#18]
Hi,
I'm trying to include GWCA in my project as in the example and I've added the include libraries in my setup. The executable now builds fine however when I execute the first function GW::Initialize() I receive the following error 
`
Exception thrown at 0x00806823 in App.exe: 0xC0000005: Access violation reading location 0x00401000.`

`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

And it's happening here

![image](https://user-images.githubusercontent.com/7779651/62404051-30cf6500-b59a-11e9-929e-86f01df1f56e.png)

So I'm pretty much stuck at the first step. 

		if (GW::Initialize()) {
			this->initialized = true;
			this->button1->Text = "Stop";
		}

Any ideas why this might be happening? I'd be happy to provide additional info to troubleshoot it if I new what is needed :)

Any help is appreciated. 

PS: I'm running as administrator and with a/v disabled completely.

**Comment by ldufr** [comment]
Did you called `GW::Scanner::Initialize` before calling `GW::Initialize` ?

It should be called from within `GW::Initialize`, but it's not right now, so that might be the reason.

**Comment by gwmai** [comment]
@reduf I tried your suggestion but I still receive the same access violation. GW:Scanner:Initialize executes correctly and GW::Initialize throws the exception.

**Comment by ldufr** [comment]
When the access violation is thrown, can you check the value of g_base and g_size ?
Also, if you go up in the call stack, can you check on which pattern it happens ?

**Comment by gwmai** [comment]
Sure,
right when the exception is thrown these are the values for pattern, g_base and g_size. 
 
pattern | 0x003fafac "V‹ñ;ðr\x4" | const char *
g_base | 4198400 | unsigned int
g_size | 4825088 | unsigned int

**Comment by ldufr** [comment]
g_base and g_size are correct, but for the pattern can you post the code at the calling site. That is the `FindPattern` that cause that. You can easily access it through your call stack.

**Comment by gwmai** [comment]
Sorry to touble you, I'm not really well versed in debugging with visual studio code so I might not be following you correctly. 

In my call stack I see :

![image](https://user-images.githubusercontent.com/7779651/62453102-48fdda80-b77a-11e9-8b8a-ad0cb5310e84.png)

It seems the function executed before this exception is thrown is GW::MemoryMgr::Scan

In that one, it's this line  that's throwing the error but there's no pattern variable here. It's a  fixed string. 

![image](https://user-images.githubusercontent.com/7779651/62453178-70ed3e00-b77a-11e9-9d3e-dfce36e90b08.png)

PS: I couldn't find any string in the code called FindPattern.

**Comment by ldufr** [comment]
I think that the problem is that GWCA only make sense if it's inside `Gw.exe`. Right now, it seems that you use it in an other process.

**Comment by gwmai** [comment]
I was under the impression that I can build my application including GWCA as a library and the initialize function would let  it hook itself to the gw.exe instance.

**Comment by ldufr** [comment]
You can build a dll including GWCA and load this dll into the game process.
