### ISSUE TITLE
PartyMgr::RespondToPartyRequest() not working

### ISSUE THREAD

**Issue by AnonymousII** [GregLando113/GWCA#19]
Hi,

I'm currently trying to accept a party invite using the GWCA function RespondToPartyRequest(true) from PartyMgr. However the behaviour is a bit strange:

- RespondToPartyRequest(true) seems to do nothing at all
- RespondToPartyRequest(false) switches to hard mode instead of declining the party request

The rest of GWCA seems to work fine, so it seems to be a problem with this particular function only. Did I miss anything? I guess calling RespondToPartyRequest(true) should be all that is required to accept an invite... Or has the packet which has to be sent in order to accept possibly been changed in one of the past updates?

Thanks in advance.

**Comment by ldufr** [comment]
This function is completely broken. Just from the signature, how could it know which party request to accept. Moreover, I've looked and the headers used in the function are off.

Anyway, I'll fix it.

**Comment by 3vcloud** [comment]
Signature for this function has been changed
