### ISSUE TITLE
How to clone and run examples eg PacketLogger in Visual Studio 2022?

### ISSUE THREAD

**Issue by NickGw99** [GregLando113/GWCA#72]
Hi 👋  I'm new to Visual Studio and C++ and am wondering how I can get the Packet Logger example project up-and-running? I currently have Visual Studio 2022 installed.

Here's what I've tried so-far:

1. Open Examples/Examples.sln in Visual Studio
2. "Solution Explorer" -> PacketLogger -> Build
    1. Error: the following warning is treated as an error: 'initializing': conversion from 'int' to 'size_t', signed/unsigned mismatch
    2. Error: the following warning is treated as an error:  enumerator 'GW::UI::EnumPreference::CharSortOrder' in switch of enum 'GW::UI::EnumPreference' is not handled (x10 more for other enum values)
    3. cannot open file C:\...\GWCA\Examples\Debug\GWCA.lib
3. "Solution Explorer" -> GWCA -> Build
    - same errors as above except for error 2.iii.
4. Change "Solution Explorer" -> GWCA -> Properties -> C/C++ -> "Treat Warnings As Errors" -> "No (/WX-)"
5. "Solution Explorer" -> GWCA -> Build
    - success
6. "Solution Explorer" -> PacketLogger -> Build
    1. LNK2001 unresolved external symbol "struct GW::Module GW::EventMgrModule" (?EventMgrModule@GW@@3UModule@1@A) PacketLogger C:\...\GWCA\Examples\PacketLogger\GWCA.lib(GWCA.obj)
    2. Error LNK2001 unresolved external symbol "struct GW::Module GW::QuestModule" (?QuestModule@GW@@3UModule@1@A)	PacketLogger	C:\...\GWCA\Examples\PacketLogger\GWCA.lib(GWCA.obj)
    3. LNK1120 2 unresolved externals PacketLogger C:\...\GWCA\Examples\Debug\PacketLogger.dll

None of that worked so then I tried running `cmake .` in the Examples directory but it only seemed to partially succeed

```sh
$ cmake .
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.35.32216.1
-- The CXX compiler identification is MSVC 19.35.32216.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (message):
  You are configuring a 64bit build, this is not supported.  Run cmake with
  `-A Win32`

-- Configuring incomplete, errors occurred!
See also "C:/.../GWCA/CMakeFiles/CMakeOutput.log".
```

Then I deleted `CMakeCache.txt` and tried cmake again with `cmake -A Win32 .` and it appeared to succeed.

```sh
$ cmake . -A Win32
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
-- The C compiler identification is MSVC 19.35.32216.1
-- The CXX compiler identification is MSVC 19.35.32216.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.../GWCA
```

Then I tried to build/run PacketLogger in Visual Studio again

- "Solution Explorer" -> PacketLogger -> Build
  - Error LNK1104 cannot open file '..\..\Debug\gwca.lib' PacketLogger C:\...\GWCA\Examples\PacketLogger\LINK

and wasn't sure where to go from there. I've probably way over-complicated it. Any help would be appreciated 😄 .

**Comment by NickGw99** [comment]
Update: was able to get the PacketLogger running by:

1. executing`cmake -A Win32 -B build .` in the root of the project
2. Opening with the built outputs `GWCA/build/GWCA.sln` Visual Studio
3. Building PacketLogger in Visual Studio: "Solution Explorer" -> PacketLogger -> Build
4. Copying `GWCA/Examples/Inject.au3` into the directory with PacketLogger's built .ddl `GWCA/build/Examples/PacketLogger/Debug`
5. Installing AutoIt
6. Executing `GWCA/build/Examples/PacketLogger/Inject.au3`.

Would love to know the proper way to do this, how to set-up another project that uses GWCA and also and also how to use with ImGui. I know the readme says to add as a git submodule to your existing but I'm not sure what else is required (eg make a `CMakeLists.txt` file similar to Gw Toolbox?).

**Comment by henderkes** [comment]
You don't have to use cmake to use gwca in your own project. Just add it as a git submodule, add the project to your existing solution and reference it in your own projects properties.

**Comment by NickGw99** [comment]
> You don't have to use cmake to use gwca in your own project. Just add it as a git submodule, add the project to your existing solution and reference it in your own projects properties.

Thanks. Looks like I need understand c++ build systems a little better to know how to proceed.
