### ISSUE TITLE
Auth server protocol key retrieval

### ISSUE THREAD

**Issue by valaphee** [GregLando113/GWCA#73]
Not directly related, but I was wondering if some knows how the current Auth server protocol rc4 key is derived, because I wanted to implement an proxy: https://github.com/valaphee/sprinkle/blob/main/src/bin/proxy.rs#L153, but couldn't figure it out yet.

**Comment by henderkes** [comment]
You're better off checking out the [Headquarters](https://github.com/3vcloud/JonsHeadquarter) project.for that.
